---
# karaf tasks file for fedora_commons
- name: karaf | Create karaf group
  group: name=karaf state=present
  tags:
    - install

- name: karaf | Create karaf user
  user: name=u_karaf group=karaf state=present
  tags:
    - install

- name: karaf | Check if karaf release has been downloaded already
  stat: 
    path: "/opt/apache-karaf-{{ karaf_version }}.tar.gz"
  register: karaf_file_download
  tags:
    - install
    - update

- name: karaf | Download karaf release file
  get_url:
    url: "{{ karaf_base_url }}/apache-karaf-{{ karaf_version }}.tar.gz"
    dest: "/opt/apache-karaf-{{ karaf_version }}.tar.gz"
  when: not karaf_file_download.stat.exists
  tags:
    - install
    - update

- name: karaf | Remove karaf tar file
  file: path=/opt/apache-karaf-{{ karaf_version }}.tar.gz state=absent
  tags:
    - remove

- name: karaf | check of /opt/apache-karaf-{{ karaf_version }} exists
  stat: 
    path: "/opt/apache-karaf-{{ karaf_version }}"
  register: karaf_dir
  tags:
    - install
    - update

- name: karaf | Remove karaf_dir
  file: path=/opt/apache-karaf-{{ karaf_version }} state=absent
  tags:
    - remove 
   
- name: karaf | Extract karaf tar file
  unarchive: src=/opt/apache-karaf-{{ karaf_version }}.tar.gz dest=/opt/ copy=no
  when: not karaf_dir.stat.exists
  tags:
    - install
    - update

- name: karaf | Create/Update Symlink
  file: src=/opt/apache-karaf-{{ karaf_version }} dest={{ karaf_base }} state=link
  tags:
    - install
    - update

- name: karaf | Remove Symlink
  file: path={{ karaf_base }} state=absent
  tags:
    - remove

- name: karaf | Ensure install_service directory exists
  file: path={{ karaf_base }}/install_service state=directory
  tags:
    - install

- name: karaf | Copy karaf_service.script to {{ karaf_base }}
  copy: src=karaf_service.script dest={{ karaf_base }}/install_service/
  tags:
    - install

- name: karaf | Copy karaf_service_install.sh to {{ karaf_base }}/install_service
  template: src=karaf_service_install.sh dest={{ karaf_base }}/install_service/karaf_service_install.sh mode=0755
  tags:
    - install

- name: karaf | Find out the current java_home
  shell: alternatives --display java | grep 'link currently points to' | sed 's/link\ currently\ points\ to\s//g' | sed 's/^\ //g' | sed 's/\/bin\/java$//g'
  register: java_home
  changed_when: false
  tags:
    - install

- name: karaf | Run karaf service installation
  shell: "export JAVA_HOME={{ java_home.stdout }} && {{ karaf_base }}/install_service/karaf_service_install.sh"
  args:
    creates: "{{ karaf_base }}/bin/karaf.service"
  tags:
    - install

- name: karaf | Add java_home to service file
  lineinfile:
    dest: "{{ karaf_base }}/bin/karaf.service"
    insertafter: ^\[Service\]$
    line: Environment=JAVA_HOME={{ java_home.stdout }} 
    regexp: ^Environment\=JAVA_HOME
    state: present
  tags:
    - install

- name: karaf | Check if the script is different between /etc/systemd and {{ karaf_base }}
  command: diff {{ karaf_base }}/bin/karaf.service /etc/systemd/system/karaf.service
  ignore_errors: yes
  register: service_changes
  changed_when: false
  tags:
    - install

- name: karaf | Copy service file to /etc/systemd/system
  command: cp {{ karaf_base }}/bin/karaf.service /etc/systemd/system
  when: service_changes.rc != 0
  args:
    creates: /etc/sytemd/system/karaf.service
  tags:
    - install

- name: karaf | Enable karaf service
  service: name=karaf state=started enabled=yes 
  tags:
    - install

# - name: karaf | Enable Maven m2 repo
  
