---
# tasks file for fedora_commons
- name: Set up roles in Tomcat
  set_fact:
    tomcat_manager_users: "{{ fedora_users }}"
    tomcat_manager_roles: "{{ fedora_roles }}"
  tags:
    - install
    - config

- name: include tomcat role
  import_role:
    name: tomcat

- name: Install prerequisites from fcrepo4-vagrant-base-box bootstrap.sh
  yum: name={{ item }} state=latest
  with_items: #htop and fish are not in the default repo
    - gcc 
    - gcc-c++
    - make
    - maven
    - openssl-devel
    - git
    - vim
    - wget
    - curl
    - tree
    - zsh
  tags:
    - install
    - upgrade
    - config

- name: Create the ingest directory
  file: path=/mnt/ingest state=directory owner={{ tomcat_user }} group={{ tomcat_group }}
  tags:
    - install
    - config

- name: Include solr
  include: solr.yml
  when: install_solr

- name: Include fuseki
  include: fuseki.yml
  when: install_fuseki

- name: Include karaf
  include: karaf.yml
  when: install_karaf
  
- name: Include determine_fedora_version 
  include: determine_fedora_version.yml
  tags:
    - install
    - upgrade

- name: Deploy fedora war
  include: deploy_fedora_war.yml
  when: True

- name: Include camel
  include: fedora_camel_toolbox.yml
  when: fedora_camel
